Created API Models
djordjevics/FuelLogHighSchool pull request #13
Opened 2023-10-06 10:53 UTC by injacmarko

Jel dobro ovako

2023-10-06 10:57 UTC, FilipZecevic approved these changes
Izgleda dobro

2023-10-06 10:59 UTC, djordjevics requested changes

2023-10-06 10:59 UTC, djordjevics commented on src/FuelLog/Models/CreateVehicle.cs
> +        public int WheelNumber;
ordinal?

Wheel number 1
Wheel number 2...

Suggestion: NumberOfWheels, WheelsCount

2023-10-06 10:59 UTC, djordjevics commented on src/FuelLog/Models/GetVehicle.cs
> +    public class GetVehicle
GetVehicleById

2023-10-06 10:59 UTC, djordjevics commented on src/FuelLog/Models/UpdateVehicle.cs
> +    public class UpdateVehicle
UpdateVehicleRequest -> da znamo šta je iz naziva.

2023-10-06 10:59 UTC, djordjevics commented on src/FuelLog/Models/Vehicle.cs
> +        public int WheelNumber;
wheelnumber?

2023-10-08 14:57 UTC, KoAleksandar approved these changes

2023-10-10 12:36 UTC, djordjevics approved these changes

2023-10-10 12:36 UTC, merged