Created Business Models
djordjevics/FuelLogHighSchool pull request #16
Opened 2023-10-09 13:00 UTC by injacmarko

2023-10-09 16:58 UTC, FilipZecevic approved these changes

2023-10-10 12:56 UTC, djordjevics requested changes

2023-10-10 12:56 UTC, djordjevics commented on src/BuisinessLogic/Models/CreateFuelLogDTO.cs
> +        public string TypeOfFuel;
Enum, please

2023-10-10 12:56 UTC, djordjevics commented on src/BuisinessLogic/Models/CreateFuelLogDTO.cs
> +        public int TruckId;
truck ?

What about car, motorcycle?

2023-10-10 12:56 UTC, djordjevics commented on src/BuisinessLogic/Models/CreateFuelLogDTO.cs
> +        public string TypeOfFuel;
type of fuel for fuel log?
One fuel log can be petrol, next fill can be diesel?

2023-10-10 12:56 UTC, djordjevics commented on src/BuisinessLogic/Models/CreateVehicleDTO.cs
> +}
missing fuel type

2023-10-10 12:56 UTC, djordjevics commented on src/BuisinessLogic/Models/FuelLogDTO.cs
> +        public int TruckId;
similar to CreateFuelLogDTO

2023-10-10 12:56 UTC, djordjevics commented on src/BuisinessLogic/Models/FuelLogDTO.cs
> +        public int Cost;
Currency

2023-10-10 12:56 UTC, djordjevics commented on src/BuisinessLogic/Models/GetFuelLogByVehicleDTO.cs
> +    public class GetFuelLogByVehicleDTO
byVehicleId

2023-10-10 12:56 UTC, djordjevics commented on src/BuisinessLogic/Models/VehicleDTO.cs
> +        public int WheelCount;
FuelType

2023-10-10 17:08 UTC, djordjevics requested changes

2023-10-10 17:08 UTC, djordjevics commented on src/BuisinessLogic/Models/FuelLogDTO.cs
> +        public enum OdometerUnit
separate file

2023-10-10 17:08 UTC, djordjevics commented on src/BuisinessLogic/Models/FuelLogDTO.cs
> +            km,
UPPERCASE

2023-10-10 17:08 UTC, djordjevics commented on src/BuisinessLogic/Models/FuelLogDTO.cs
> +        public enum AmountFilledUnit
separate file

2023-10-10 17:08 UTC, djordjevics commented on src/BuisinessLogic/Models/Enums/CostCurrency.cs
> +using System.Linq;
unused usings

2023-10-10 17:08 UTC, djordjevics commented on src/BuisinessLogic/Models/Enums/AmountFilledUnit.cs
> +using System.Linq;
unused usings

2023-10-10 17:08 UTC, djordjevics commented on src/BuisinessLogic/Models/Enums/FuelType.cs
> +using System.Linq;
unused usings

2023-10-10 17:08 UTC, djordjevics commented on src/BuisinessLogic/Models/Enums/OdometerUnit.cs
> +using System.Linq;
unused usings

2023-10-11 14:52 UTC, djordjevics approved these changes

2023-10-11 14:52 UTC, merged