Created data layer intefaces
djordjevics/FuelLogHighSchool pull request #21
Opened 2023-10-10 13:46 UTC by FilipZecevic

2023-10-11 12:47 UTC, injacmarko requested changes

2023-10-11 12:47 UTC, injacmarko commented on src/Data/Intefaces/IFuelLog.cs
> +    internal interface IFuelLog
Internal?

2023-10-11 12:47 UTC, injacmarko commented on src/Data/Intefaces/IVehicle.cs
> +    internal interface IVehicle
Same here

2023-10-11 12:47 UTC, injacmarko commented on src/BuisinessLogic/Intefaces/IFuelLog.cs
> +        public interface IFuelLog
Interface in an interface?

2023-10-11 12:47 UTC, injacmarko commented on src/BuisinessLogic/Intefaces/IVehicle.cs
> +    public interface IVehicle
here also

2023-10-11 12:47 UTC, injacmarko commented on src/BuisinessLogic/Intefaces/IVehicle.cs
> +            void AddVehicle(Vehicle vehicle);
VehicleDTO

2023-10-11 12:47 UTC, injacmarko commented on src/BuisinessLogic/Intefaces/IFuelLog.cs
> +            void AddFuelLogToVehicle(int id, FuelLog fuel_log);
FuelLogDTO

2023-10-12 13:05 UTC, injacmarko approved these changes
Looks good now

2023-10-12 17:06 UTC, KoAleksandar approved these changes

2023-10-12 17:07 UTC, merged