Mappers
djordjevics/FuelLogHighSchool pull request #41
Opened 2023-10-16 10:08 UTC by injacmarko

2023-10-16 10:10 UTC, KoAleksandar approved these changes

2023-10-16 10:14 UTC, djordjevics requested changes

2023-10-16 10:14 UTC, djordjevics commented on src/BuisinessLogic/Converter.cs
> +        public static double MiToKm(this double Mi)
getter in class directly

2023-10-16 10:14 UTC, djordjevics commented on src/BuisinessLogic/Converter.cs
> +        public static double MiToKm(this double Mi)
count for all methodss

2023-10-16 10:14 UTC, djordjevics commented on src/BuisinessLogic/Mappers/APIToBusiness.cs
> +        public static VehicleDTO toVehicleDTO(this CreateVehicle create)
naming..

create -> request or just vehicle

2023-10-16 10:14 UTC, djordjevics commented on src/BuisinessLogic/Mappers/APIToBusiness.cs
> +        public static FuelLogDTO toFuelLogDTO(this CreateFuelLog create)
same, naming

2023-10-16 10:14 UTC, djordjevics commented on src/BuisinessLogic/Mappers/BusinessToData.cs
> +        public static FuelLogData toFuellogData(this FuelLogDTO dto)
can be simplified

2023-10-16 10:14 UTC, djordjevics commented on src/BuisinessLogic/Mappers/DataToBusiness.cs
> +                FuelType = (FuelType)Enum.Parse(typeof(FuelType), data.FuelType)
Parse<FuelType>(out enumValue) ?

2023-10-16 10:26 UTC, FilipZecevic approved these changes

2023-10-17 21:13 UTC, FilipZecevic approved these changes

2023-10-18 09:38 UTC, djordjevics approved these changes

2023-10-18 09:38 UTC, merged